import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Input } from "@/components/ui/input"
import Image from "next/image";
import Link from "next/link";
import { ShoppingCart } from 'lucide-react';
import Header from "./component/Header";
import Footer from "./component/Footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body  className={` p-14 pt-7 `}>
      <Header/>
       
       {children}
       
     <Footer/>
      
        
        </body>
        <footer className="bg-gray-500 flex justify-center py-5 items-end">
          <p>&copy; 2023 - All rights reserved.</p>
        </footer>
    </html>
  );
}